### ISSUE TITLE
Docker compose installation doesn't run

### ISSUE THREAD

**Issue by yelizariev** [cenit-io/cenit#2674]
## Context

I cannot install cenit

## Expected Behavior

cenit runs at port 3000 (or any other port)

## Actual Behavior

`cenit_cenit_1 exited with code 1
`

## Possible Fix

No idea

## Steps to Reproduce

```
docker-compose build
docker-compose up

```
## Your Environment

```
ivann@ivann-360:~/odoo/cenit$ docker --version
Docker version 18.09.6, build 481bc77
ivann@ivann-360:~/odoo/cenit$ docker-compose --version
docker-compose version 1.24.0, build 0aa59064

```

* Version used: latest
* Gemfile and Gemfile.lock as text in a Gist: —
* Any relevant stack traces ("Full trace" preferred):
```

urllib3.connectionpool._make_request: http://localhost:None "GET /v1.38/events?filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dcenit%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D HTTP/1.1" 200 None
compose.cli.verbose_proxy.proxy_callable: docker events -> <docker.types.daemon.CancellableStream object at 0x7ff177ff29b0>
compose.cli.verbose_proxy.proxy_callable: docker wait <- ('cffae999aaa1a024361bb55cb2856c3bd3da3ad98d5de2bc40762933b242f0e9')
compose.cli.verbose_proxy.proxy_callable: docker inspect_container <- ('cffae999aaa1a024361bb55cb2856c3bd3da3ad98d5de2bc40762933b242f0e9')
urllib3.connectionpool._make_request: http://localhost:None "POST /v1.38/containers/cffae999aaa1a024361bb55cb2856c3bd3da3ad98d5de2bc40762933b242f0e9/wait HTTP/1.1" 200 None
compose.cli.verbose_proxy.proxy_callable: docker wait -> {'Error': None, 'StatusCode': 1}
cenit_cenit_1 exited with code 1
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.38/containers/cffae999aaa1a024361bb55cb2856c3bd3da3ad98d5de2bc40762933b242f0e9/json HTTP/1.1" 200 None
compose.cli.verbose_proxy.proxy_callable: docker inspect_container -> {'AppArmorProfile': 'docker-default',
 'Args': ['exec', 'unicorn', '-c', 'config/unicorn.rb'],
 'Config': {'ArgsEscaped': True,
            'AttachStderr': False,
            'AttachStdin': False,
            'AttachStdout': False,
            'Cmd': ['bundle', 'exec', 'unicorn', '-c', 'config/unicorn.rb'],
            'Domainname': '',
            'Entrypoint': None,
            'Env': ['ENABLE_RERECAPTCHA=false',
...
```

**Comment by BhagiLimbu** [comment]
I'm facing a similar issue on my local PC. Has anyone resolved a similar issue before?

**Comment by TFAssKID** [comment]
This problem has evolved over time because we continue to develop our platform ... so I will try to explain the problem piece by piece... generally this problem is shown when the application cannot connect to the database ... previously we had the following configuration on **config/mongoid.yml**:
```yaml
production:
  clients:
    default:
      database: <%= ENV['DB_PROD'] || 'cenit_prod' %>
      hosts:
        - <%= ENV['DB_PORT'] || 'localhost:27017' %>
```
in this case we need to set the followin environment variables **DB_PORT** with the conection to mongodb and **DB_PROD** with the name of production DB.
This configuration is old the new configuration is the following:
```yaml
production:
  clients:
    default:
     # The standard MongoDB connection URI allows for easy
     # replica set connection setup.
     # Use environment variables or a config file to keep your
     # credentials safe e.g. <%= ENV['MONGODB_URI'] %>.
     uri: <%= ENV['MONGODB_URI'] %>

     options:
       # The default timeout is 5, which is the time in seconds
       # for a connection to time out.
       # We recommend 15 because it allows for plenty of time
       # in most operating environments.
       connect_timeout: 15
```
in this case you need to put the **URI** of your external database.
>**NOTE:**
If you do not provide a secure connection (SSL) the external database will refused your connection and by consequence the cenit app will crash
